branches:
  - nonexistent-branch
  - master

host:
  distro: centos/7/cloud

extra-repos:
  - name: centos-continuous
    baseurl: https://ci.centos.org/artifacts/sig-atomic/rdgo/centos-continuous/build/

packages:
  - skopeo

tests:
  - rpm -q skopeo
