branches:
  - nonexistent-branch
  - master
  - jlebon-patch-7

host:
  distro: centos/7/cloud

context: 'My context'

tests:
  - sleep 10
  - echo hello world
  - echo "asdf" > file.log
  - mkdir dir
  - echo "zxcv" > dir/file.log

timeout: 20s

artifacts:
  - file.log
  - dir
