branches:
  - nonexistent-branch
  - master
  - jlebon-patch-7

host:
  distro: centos/7/cloud

context: 'My context'

packages:
  - make
  - gcc

tests:
  - echo hello world
  - echo "asdf" > file.log
  - mkdir dir
  - echo "zxcv" > dir/file.log

artifacts:
  - file.log
  - dir
