branches:
  - nonexistent-branch
  - master
  - jlebon-patch-7

host:
  distro: fedora/24/cloud

tests:
  - echo hello world
  - echo "asdf" > file
  - mkdir dir
  - echo "zxcv" > dir/file

artifacts:
  - file
  - dir
