branches:
  - master

host:
  distro: fedora/24/atomic

tests:
  - ostree admin unlock
  - >
      docker run --privileged
      -v /root:/root -v $PWD:/code -v /:/host
      --workdir /code fedora:24 ./rhci.sh
      #- ENABLE_DESTRUCTIVE=1 ./test.sh
  - ./test.sh

artifacts:
  - tests.log
